# This file was generated by GoReleaser. DO NOT EDIT.
cask "drizz" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "b2a7fa70859ec5063ed039e50fd7d951868c768cce4338d63167684993d1cdb2"
      url "https://github.com/DrizzDev/releases/releases/download/v#{version}/drizz-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "aa55f5e895f9183ffb94716ef53169a37099c22e689743cf0ddfa7c6664e7db9"
      url "https://github.com/DrizzDev/releases/releases/download/v#{version}/drizz-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d81a18d3cf31c732caf31bfaff014bfeef01e620d8d3282ea32c9772a2a82983"
      url "https://github.com/DrizzDev/releases/releases/download/v#{version}/drizz-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "9bd33dc2c3401d0073a53f1ffd31ffc835fd4f9a1b96ed1b5cb754aa1b9e8f99"
      url "https://github.com/DrizzDev/releases/releases/download/v#{version}/drizz-linux-arm64.tar.gz"
    end
  end

  name "drizz"
  desc "Drive connected devices from AI coding assistants and the command line, recorded locally."
  homepage "https://drizz.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drizz"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/drizz"]
  end

  # No zap stanza required

end
