# This file was generated by GoReleaser. DO NOT EDIT.
cask "drizz" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "b5ed419b9b32a3aa717678307c464cc7147a7d41b0c8a090a59b707221ad1f80"
      url "https://github.com/DrizzDev/platform/releases/download/v#{version}/drizz-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "2e1cfb5d34d76ff84a96b5101146ea0ca309e0f774b1e0c563bbc2790045771f"
      url "https://github.com/DrizzDev/platform/releases/download/v#{version}/drizz-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dc6dba17cf94a23aebddb322b9e5c1bea281a0a192e2454a2cae670c4617477e"
      url "https://github.com/DrizzDev/platform/releases/download/v#{version}/drizz-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "7a80aa6351d81cf079437cae6a634da90bb209e06316c47107cbd788d9420dea"
      url "https://github.com/DrizzDev/platform/releases/download/v#{version}/drizz-linux-arm64.tar.gz"
    end
  end

  name "drizz"
  desc "Drive connected devices from AI coding assistants and the command line, recorded locally."
  homepage "https://drizz.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drizz"

  # No zap stanza required

end
