# This file was generated by GoReleaser. DO NOT EDIT.
cask "drizz" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "7ba7cf137f364abd07eeca6dbf3a1490ebc63e01e64d071d6dde0ba283f6924c"
      url "https://github.com/DrizzDev/releases/releases/download/v#{version}/drizz-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "8ab1e7ed58978293fa5d9e81b93912f13ad434dba7a0623c7919c24a434ddb4a"
      url "https://github.com/DrizzDev/releases/releases/download/v#{version}/drizz-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "75dfe00e376b51aa389a93a792e5a8baf381bb72e68b7686c6cd8941609f45e3"
      url "https://github.com/DrizzDev/releases/releases/download/v#{version}/drizz-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "85a52cbc37683307a4e1466a003193a27767628774d7c71bbb9c7ea6f247856a"
      url "https://github.com/DrizzDev/releases/releases/download/v#{version}/drizz-linux-arm64.tar.gz"
    end
  end

  name "drizz"
  desc "Drive connected devices from AI coding assistants and the command line, recorded locally."
  homepage "https://drizz.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drizz"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/drizz"]
  end

  # No zap stanza required

end
